# Generated by Django 4.1.3 on 2022-11-20 14:10

import backend.models
import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField()),
                ('date_of_birth', models.DateField(null=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', backend.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('definition', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAdmin',
            fields=[
                ('admin_username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('height', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('avatar', models.IntegerField(default=1)),
                ('past_illnesses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None)),
                ('chronic_diseases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None)),
                ('undergone_operations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None)),
                ('used_drugs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reviewed_date', models.DateField(null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL)),
                ('reporter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_user', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_by', to='backend.customadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_username', models.CharField(max_length=50, unique=True)),
                ('banned_by', models.CharField(default=None, max_length=50, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.memberinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=100, null=True)),
                ('verified', models.BooleanField(default=False, max_length=100)),
                ('profile_picture', models.TextField(null=True)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
