# Generated by Django 4.1.2 on 2022-10-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='member',
            name='banned_by',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
