# Generated by Django 4.1.2 on 2022-10-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_member_avatar_alter_member_banned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
