# Generated by Django 4.1.2 on 2022-11-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='member',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='member',
            name='info',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviewed_by',
        ),
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
