# Generated by Django 4.1.2 on 2022-11-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.IntegerField(default=1),
        ),
    ]
