# Generated by Django 4.1.2 on 2022-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_downvoted_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='document',
            field=models.TextField(default=None, null=True),
        ),
    ]
