# Generated by Django 4.1.2 on 2022-10-23 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_admin_username_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_date',
            field=models.DateField(null=True),
        ),
    ]
