# Generated by Django 4.1.2 on 2022-10-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_report_date_report_reviewed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='firstname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
