# Generated by Django 4.1.3 on 2022-12-17 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customuser_followed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='downvoted_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='downvoted_comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='downvoted_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followed_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upvoted_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upvoted_comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='upvoted_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
    ]
