# Generated by Django 4.1.2 on 2022-12-22 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_customuser_downvoted_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
    ]
