# Generated by Django 4.1.2 on 2022-12-24 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_customuser_bookmarked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, null=True, size=None),
        ),
    ]
