# Generated by Django 4.1.2 on 2022-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
