# Generated by Django 4.1.2 on 2022-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_latitude_comment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commented_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
