# Generated by Django 4.1.2 on 2022-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_commented_by_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='longitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0, null=True),
        ),
    ]
