# Generated by Django 4.1.2 on 2022-12-25 01:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default=list, null=True, size=None),
        ),
    ]
