# Generated by Django 4.1.2 on 2022-12-17 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('POST', 'POST'), ('ARTICLE', 'ARTICLE')], max_length=50)),
                ('source_id', models.IntegerField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
