# Generated by Django 4.1.2 on 2022-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_rename_date_textannotation_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textannotation',
            name='author_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
