# Generated by Django 4.1.2 on 2022-12-18 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0004_textannotation_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('POST', 'POST'), ('ARTICLE', 'ARTICLE')], max_length=50)),
                ('source_id', models.IntegerField()),
                ('author_link', models.CharField(default='', max_length=200)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('value', models.TextField(default='')),
                ('date_created', models.DateTimeField()),
                ('purpose', models.CharField(default='', max_length=100)),
                ('pixels', models.CharField(default='', max_length=200)),
                ('photo_url', models.CharField(default='', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
