# Generated by Django 4.1.2 on 2022-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_imageannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='textannotation',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='textannotation',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
