# Generated by Django 4.1.2 on 2022-11-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimages',
            old_name='post',
            new_name='article',
        ),
    ]
