# Generated by Django 4.1.2 on 2022-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_label'),
        ('articles', '0003_rename_post_articleimages_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(to='backend.label'),
        ),
    ]
