# Generated by Django 4.0.4 on 2022-05-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_nofdownvotes_comment_nofupvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nofdownvotes',
            new_name='nof_downvotes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='nofupvotes',
            new_name='nof_upvotes',
        ),
    ]
