# Generated by Django 4.0.4 on 2022-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='covid19cases',
            field=models.JSONField(default=dict),
        ),
    ]
