# Generated by Django 4.0.4 on 2022-05-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_covid19cases'),
        ('post', '0002_alter_post_covid19cases_alter_post_timestamp'),
    ]

    operations = [
    ]
